# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Note' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaLumberjack/Swift'

  # Pods for Note

  target 'NoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
